#vaidate-yaml: false
project:
  type: book
  output-dir: docs # output directory
  preview:
    port: 4300 # preview on port 4300

book:
  title: "Quantitative Text Analysis for Linguistics"
  subtitle: "Reproducible Research using R"
  cover-image: assets/images/cover.png
  date: last-modified
  date-format: long # long, short, or custom
  author:
    - name: Jerid Francom
      affiliation: Wake Forest University
      email: francojc@wfu.edu
      url: https://francojc.github.io
      role: author
  sidebar:
    style: docked # docked, floating, or none
    background: light # light or dark
    collapse-level: 2 # 0 = no collapse, 1 = collapse sections, 2 = collapse sections + subsections, etc.
    tools:
      - icon: github # github, twitter, or rss
        href: https://github.com
  output-file: "qtal-manuscript" # name of output file (pdf, epub, word)
  chapters:
    - index.qmd
    - preface.qmd
    - part: orientation.qmd # Part I
      chapters:
        - text-analysis.qmd
    - part: foundations.qmd # Part II
      chapters:
        - understanding-data.qmd
        - approaching-analysis.qmd
        - framing-research.qmd
    - part: preparation.qmd # Part III
      chapters:
        - acquire-data.qmd
        - curate-datasets.qmd
        - transform-datasets.qmd
    - part: analysis.qmd # Part IV
      chapters:
        - exploration.qmd
        - prediction.qmd
        - inference.qmd
    - part: communication.qmd # Part V
      chapters:
        - reporting.qmd
        - collaboration.qmd
    - references.qmd # References
  appendices: # Appendices
    - data.qmd

number-depth: 3 # 0 = no numbering, 1 = section, 2 = section + subsection, etc.
crossref:
  lst-title: "Block" # title for code blocks
  lst-prefix: "Block"

bibliography: [textbook.bib, packages.bib] # bibliography files

# filters:
#   - search-replace
#   - multibib

# search-replace:
#   +quarto: "[Quarto](https://quarto.org)"
#   +outcomes: "## {{< fa regular list-alt >}} Outcomes"
#   +hello: "Hello world"
#   +qtalr: "https://lin380.github.io/tadr"

# bibliography:
#   main: references.bib
#   packages: packages.bib

#callout-appearance: simple
#callout-icon: false

format:
  html:
    # include-in-header: assets/includes/indexing.html # .js to produce indices (??)
    # Theme attributes: https://bootswatch.com/
    theme:
      light: flatly
      # dark: darkly # changes syntax highlighting
    css: assets/css/style.css # custom css
    fontsize: 1.1em # font size
    code-link: true # link code to source
    code-overflow: wrap # wrap or scroll
    copy-code: true # copy code
    code-block-background: true
    text-overflow: wrap # wrap or scroll

    language:
      title-block-published: "Updated"
    
    comments: 
      hypothesis: true
  pdf:
    # pandoc-args: "--no-highlight"
    author: "Jerid Francom"
    fig-pos: h # h = here, t = top, b = bottom
    fig-width: 5 # figure width
    # fig-format: svg # figure format
    documentclass: latex/krantz # latex document class
    # documentclass: scrbook
    font-family: libertinus
    font-size: 11pt
    include-in-header: latex/preamble.tex
    include-after-body:
      text: |
        \printindex
    code-block-bg: true # code block background
    code-block-border-left: true # code block border
    highlight-style: monochrome # highlight style
    colorlinks: false # color links
    links-as-notes: true # links as footnotes
    keep-tex: true # keep tex file

execute:
  cache: true # cache results (default): true, false, or refresh
  echo: true # echo code (default)
  warning: false # show warnings (default)
  message: false # show messages (default)
  freeze: auto # freeze rendering (default) -- only on source change

knitr:
  opts_chunk:
    comment: ">"
    paged.print: TRUE
    fig.align: "center"
    fig.width: 5
    fig.height: 3
    out.width: "75%"
