# Project ---------------------------------------------------------------------
project:
  type: book
  output-dir: _book
  preview:
    port: 4300

# Book ------------------------------------------------------------------------
book:
  title: "An Introduction to Quantitative Text Analysis for Linguistics"
  subtitle: "Reproducible Research using R"
  cover-image: assets/images/cover.drawio.png
  cover-image-alt: "Book cover with title and subtitle"
  favicon: assets/images/logo.png
  output-file: qtalr-manuscript
  downloads: [pdf]
  sharing: [facebook, twitter]
  open-graph: true
  search: true
  reader-mode: true
  bread-crumbs: false
  repo-url: https://github.com/qtalr/book
  repo-actions: [source, edit, issue]
  issue-url: https://github.com/qtalr/book/issues
  repo-link-target: "_blank"
  date: last-modified
  date-format: long
  author:
    - name: Jerid Francom
      affiliation: Wake Forest University
      email: francojc@wfu.edu
      url: https://francojc.github.io
      role: author
      orcid: 0000-0001-5972-6330
  publisher: Routledge Press
  sidebar:
    style: docked
    background: light
    collapse-level: 2
  chapters:
    - index.qmd
    - part_0/preface.qmd
    - part: part_1/index.qmd      # Part I: Orientation
      chapters:
        - part_1/1_text.qmd
    - part: part_2/index.qmd      # Part II: Foundations
      chapters:
        - part_2/2_data.qmd
        - part_2/3_analysis.qmd
        - part_2/4_research.qmd
    - part: part_3/index.qmd      # Part III: Preparation
      chapters:
        - part_3/5_acquire.qmd
        - part_3/6_curate.qmd
        - part_3/7_transform.qmd
    - part: part_4/index.qmd      # Part IV: Analysis
      chapters:
        - part_4/8_explore.qmd
        - part_4/9_predict.qmd
        - part_4/10_infer.qmd
    - part: part_5/index.qmd      # Part V: Communication
      chapters:
        - part_5/11_contribute.qmd
    - references.qmd              # References

# References and numbering ------------------------------------------
crossref:
  lst-title: "Snippet"
  lst-prefix: "Snippet"
  appendix-title: "App"
  appendix-delim: ":"
bibliography: [textbook.bib, textbook-pkgs.bib, textbook-pkgs-add.bib]
csl: assets/apa.csl
code-annotations: false
code-line-numbers: false
number-depth: 2

# Formats ---------------------------------------------------------------------
format:
  # HTML ----
  html:
    css: assets/css/mini.css
    code-overflow: wrap
    code-link: true
    language:
      title-block-published: "Updated"
    link-external-icon: false
    comments:
      hypothesis: true
  # LaTeX ----
  pdf:
    documentclass: latex/krantz
    classoption: krantz2
    monofont: "Hack"
    monofontoptions: "Scale=0.75"
    toc-depth: 3
    include-in-header: latex/preamble.tex
    include-before-body: latex/frontmatter.tex
    include-after-body:
      text: |
        \printindex
    highlight-style: monochrome
    code-block-bg: "#f8f8f8"
    fig-pos: '!htb'
    fig-dpi: 300
    colorlinks: false
    links-as-notes: true
    link-citations: true
    keep-tex: true
    latex-clean: false

# Pandoc ---------------------------------------------------------------------
execute:
  freeze: auto
  warning: false
  message: false

# Figures ---------------------------------------------------------------------
fig-width: 4
fig-asp: 0.75

# Engine ---------------------------------------------------------------------
knitr:
  opts_chunk:
    comment: ""
    out.width: NULL
