project:
  type: book
  output-dir: docs
  preview:
    port: 4300

book:
  title: "Quantitative Text Analysis for Linguistics"
  subtitle: "Reproducible Research using R"
  cover-image: assets/cover.png
  date: last-modified
  date-format: long
  author:
    -name: "Jerid Francom"
    -orcid: "0000-0001-5972-6330"
  sidebar:
    style: docked
    background: light
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com
  output-file: "qtal-manuscript"
  chapters:
    - index.qmd
    - preface.qmd
    - part: orientation.qmd 
      chapters:
        - text-analysis.qmd
    - part: foundations.qmd 
      chapters:
        - understanding-data.qmd
        - approaching-analysis.qmd
        - framing-research.qmd
    - part: preparation.qmd
      chapters:
        - acquire-data.qmd
        - curate-datasets.qmd
        - transform-datasets.qmd
    - part: analysis.qmd
      chapters:
        - exploration.qmd
        - prediction.qmd
        - inference.qmd
    - part: communication.qmd
      chapters:
        - reporting.qmd
        - collaboration.qmd
    - references.qmd
  appendices:
    - data.qmd

comments:
  hypothesis: false
crossref:
  lst-title: "Block"
  lst-prefix: "Block"
bibliography: [references.bib, packages.bib]

#callout-appearance: simple
#callout-icon: false

format:
  html:
    css: assets/style.css
    fontsize: 1.1em
    theme:
      light: flatly
      dark: darkly
    code-link: true
    code-overflow: wrap
    code-block-background: true
    language:
      title-block-published: "Updated"
  pdf:
    fig-pos: h
    documentclass: latex/krantz
    include-in-header: latex/preamble.tex
    include-after-body:
      text: |
        \printindex
    code-block-bg: true
    colorlinks: true
    keep-tex: true


execute:
  cache: false
  echo: true
  warning: false
  message: false
  freeze: auto

knitr:
  opts_chunk:
    comment: "#>"
    out.width: "90%"
    paged.print: TRUE
    fig.align: 'center'
