# Project ---------------------------------------------------------------------
project:
  type: book
  output-dir: docs
  preview: 
    port: 4300

# Book ------------------------------------------------------------------------
book:
  title: "An Introduction to Quantitative Text Analysis for Linguistics"
  subtitle: "Reproducible Research using R"
  cover-image: assets/images/cover.drawio.png
  output-file: qtalr-manuscript
  downloads: [pdf]
  search: true
  reader-mode: true
  repo-url: https://github.com/qtalr/book
  repo-actions: [edit, issue]
  issue-url: https://github.com/qtalr/book/issues
  date: last-modified
  date-format: long
  author:
    - name: Jerid Francom
      affiliation: Wake Forest University
      email: francojc@wfu.edu
      url: https://francojc.github.io
      role: author
  publisher: Routledge Press
  sidebar:
    style: docked
    background: light
    collapse-level: 2
  chapters:
    - index.qmd
    - preface.qmd
    - part: orientation.qmd # Part I
      chapters:
        - text-analysis.qmd
    - part: foundations.qmd # Part II
      chapters:
        - understanding-data.qmd
        - approaching-analysis.qmd
        - framing-research.qmd
    - part: preparation.qmd # Part III
      chapters:
        - acquire-data.qmd
        - curate-datasets.qmd
        - transform-datasets.qmd
    - part: analysis.qmd # Part IV
      chapters:
        - exploration.qmd
        - prediction.qmd
        - inference.qmd
    - part: communication.qmd # Part V
      chapters:
        - reporting.qmd
        - collaboration.qmd
    - references.qmd # References
  appendices: # Appendices
    - data.qmd
    - feedback.qmd

# References ------------------------------------------------------------------
number-depth: 3
bibliography: [textbook.bib, packages.bib]
code-annotations: false
crossref:
  lst-title: "File" 
  lst-prefix: "File"
code-line-numbers: false

# Formats ---------------------------------------------------------------------
format:
  # HTML ----
  html:
    css: assets/css/mini.css # (edit)
    code-overflow: wrap
    code-link: true
    language:
      title-block-published: "Updated"
    link-external-icon: false
    comments:
      hypothesis: true
  # LaTeX ----
  pdf:
    documentclass: scrreport
    monofont: "PT Mono"
    monofontoptions: "Scale=0.8"
    number-sections: true
    number-depth: 2
    include-in-header: latex/preamble.tex
    include-after-body:
      text: | 
        \printindex

    highlight-style: monochrome
    code-block-bg: "#f9f9f9"
    fig-pos: 'H'
    fig-dpi: 300
    colorlinks: false 
    links-as-notes: true
    link-citations: true
    keep-tex: true

# Pandoc ---------------------------------------------------------------------
execute: 
  cache: true
  freeze: auto
  warning: false 
  message: false

fig-width: 4
fig-asp: 1

knitr: 
  opts_chunk:
    comment: ">"
    out.width: NULL
