#vaidate-yaml: false
project:
  type: book
  output-dir: docs # output directory
  preview:
    port: 4300 # preview on port 4300

book:
  title: "Quantitative Text Analysis for Linguistics"
  subtitle: "Reproducible Research using R"
  cover-image: assets/cover.png
  date: last-modified
  date-format: long
  author:
    -name: "Jerid Francom"
    -orcid: "0000-0001-5972-6330"
  sidebar:
    style: docked
    background: light
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com
  output-file: "qtal-manuscript" # name of output file (pdf, epub, word)
  chapters:
    - index.qmd
    - preface.qmd
    - part: orientation.qmd # Part I
      chapters:
        - text-analysis.qmd
    - part: foundations.qmd # Part II
      chapters:
        - understanding-data.qmd
        - approaching-analysis.qmd
        - framing-research.qmd
    - part: preparation.qmd # Part III
      chapters:
        - acquire-data.qmd
        - curate-datasets.qmd
        - transform-datasets.qmd
    - part: analysis.qmd # Part IV
      chapters:
        - exploration.qmd
        - prediction.qmd
        - inference.qmd
    - part: communication.qmd # Part V
      chapters:
        - reporting.qmd
        - collaboration.qmd
    - references.qmd # References
  appendices: # Appendices
    - data.qmd

comments:
  hypothesis: false
crossref:
  lst-title: "Block"
  lst-prefix: "Block"

bibliography: [references.bib, packages.bib]

# filters:
#   - multibib

# bibliography:
#   main: references.bib
#   packages: packages.bib

#callout-appearance: simple
#callout-icon: false
number-depth: 3 # 0 = no numbering, 1 = section, 2 = section + subsection, etc.

format:
  html:
    css: assets/style.css
    fontsize: 1.1em
    theme:
      light: flatly
      dark: darkly
    code-link: true
    code-overflow: wrap
    code-block-background: true
    language:
      title-block-published: "Updated"
  pdf:
    fig-pos: h # h = here, t = top, b = bottom
    documentclass: latex/krantz # latex document class
    include-in-header: latex/preamble.tex
    include-after-body:
      text: |
        \printindex
    code-block-bg: true
    colorlinks: true
    keep-tex: true # keep tex file

execute:
  cache: false # cache results (default)
  echo: true # echo code (default)
  warning: false # show warnings (default)
  message: false # show messages (default)
  freeze: auto # freeze rendering (default) -- only on source change

knitr:
  opts_chunk:
    comment: "#>"
    # out.width: "90%"
    paged.print: TRUE
    fig.align: "center"
    fig.width: 5
    fig.height: 3
